### ISSUE TITLE
Cool little code

### ISSUE THREAD

**Issue by GolddolphinSKB-Fexcraftian** [Eelviny/nxt-python#100]
Just wanna share this cool little code I made.... not sure where else to.

[https://www.dropbox.com/sh/aq8jnk33y7tq8cu/AAAX_XAN5Sp4ctys04hNs88Ka?dl=0](https://www.dropbox.com/sh/aq8jnk33y7tq8cu/AAAX_XAN5Sp4ctys04hNs88Ka?dl=0)
 
It loads a "Song" from a csv in its own format, then plays the sound on the NXT, ATM I have programmed it to play "Smells like teen spirit" by nirvarna.

If anyone is stuck for Ideas, (Polyphony? :) )

**Comment by Eelviny** [comment]
Nice little piece of code!

I think the best place to put something like this would be in the Wiki - add a new "projects" page, and put links to Github projects or Gists in there.
