### ISSUE TITLE
programming from python

### ISSUE THREAD

**Issue by Claireles** [Eelviny/nxt-python#105]
Hello,
I would like to import on the nxt robot a python programm which would enable the nxt robot to take the shortest path to go from a point A to a point B in a room. So actually, I made a programm which gives me the path in a list. Now, I guess I need to create another programm thanks to the fonctions I found in the nxt folder, isn't it? As a consequence I thought this: I could just use Lego Mindstorms Education NXT Programming and the robot would react as if I had used python-nxt...  Can you help me please? Thank you.

**Comment by GolddolphinSKB-Fexcraftian** [comment]
You don't "Import" it to the brick as such, Nxt-Python acts as a controller to the brick, sending commands like "Move motor" and such.

A computer must therefore be connected to do it.
Look at some examples, and try and adapt them
