### ISSUE TITLE
Update PyPi version

### ISSUE THREAD

**Issue by richin13** [Eelviny/nxt-python#108]
I was having a nightmare with nxt-python in Arch Linux because of **Invalid syntax** errors, then I realized that PyPi version of nxt-python is outdated (version 2.2.2 at the time)

Can you @Eelviny please update it to version 3.0?

Thanks

**Comment by GolddolphinSKB-Fexcraftian** [comment]
A way to obtain it, is to download the current version from github, then in terminal [Or whatever command line your OS has]

run: cd (Directory of download)
then for python3: python3 setup.py install
if your using python2, write python2, e.t.c.

**Comment by richin13** [comment]
Absolutely. That's exactly what I'm doing. 
The issue here is that the PyPi version is outdated so you cannot list nxt-python in the requirements.txt of a project, for example.
In my case, I didn't notice the PyPi version was outdated and I was relying on it, thus the errors and bugs.

**Comment by Eelviny** [comment]
Hi, was on holiday for half a year.

I'm going to close this issue as duplicate, as there are many well known problems with the Python3 version that I don't have time to address personally. I have enough time to manage issues and pull requests, which I will accept gladly!
