### ISSUE TITLE
RCX rotation sensor

### ISSUE THREAD

**Issue by pmu5757** [Eelviny/nxt-python#119]
Hellow,
I connected and old RCX rotation sensor to my NXT with an adaptation cable.
With NXC, I know how to use it, but not with nxt-python.
Thank you for your help.
Best regards,
Pascal.

**Comment by pmu5757** [comment]
Hello, I found the solution : I created a new sensor class called "Angle" using Type.ANGLE, Mode.ANGLE_STEPS
Here is my code if it could interest someone.

class Angle(BaseAnalogSensor):

    def __init__(self, brick, port):
        super(Angle, self).__init__(brick, port)
        self.set_input_mode(Type.ANGLE, Mode.ANGLE_STEPS) 

    def get_angle(self):
        return self.get_input_values().scaled_value	  
 
    get_sample = get_angle

**Comment by auryan898** [comment]
which file did you add this code to?

**Comment by pmu5757** [comment]
Hello,
I wrote it in my own code, not in any library.
Best regards,
Pascal.

**Comment by Eelviny** [comment]
Going to mark this as enhancement, but close this issue - if I feel like it in the future, I'll dig it up and put it in mainline.
