### ISSUE TITLE
Run Program on Brick

### ISSUE THREAD

**Issue by LeonHeTheFirst** [Eelviny/nxt-python#131]
I'm new to both the NXT brick and NXT-Python, but as far as I've seen, anything written with NXT-Python has to be run from a host computer connected to the brick via either USB or Bluetooth. Is there any way to run the program on the brick itself? (e.g. convert python code to rxe, then transfer onto brick and run there)

**Comment by auryan898** [comment]
Nope. You're better off looking at NXC or lejos for that.  nxt-python is specifically for computer to brick connection and control.
