### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Nathan1123** [Eelviny/nxt-python#138]
I am very sorry that this is being listed as an "Issue" when there is no actual error involved. I wish I could just email the developer(s) with this _very simple_ question, but alas I can't do that.

Is there any exact documentation on all the current functions/objects used in the nxt library? I see some functions utilized in the examples folder, so I know there is at least functions for motors, finding brick, a few sensors, sending a message and making a musical tone. That's great. But I have no idea what all the possible inputs are for these functions or what other functions are implemented. I mean, literally any python library has this kind of exact documentation, so I feel very blind that I can't find it anywhere. And if it doesn't exist, I see no way how anyone is supposed to be able to make it useful.

**Comment by GolddolphinSKB-Fexcraftian** [comment]
No up to date documentation exists as far as I know - The best resource is the examples.
There is more functionality than just the examples, but most of it is advanced stuff, where actually reading the library code is the wise thing to do.

Most things the common user would want to do is in the examples. However if there's something you need more help with, feel free to make an issue here.

https://github.com/Eelviny/nxt-python/wiki/Where-to-find-help

Also, I forgot to note that documentation for the scripts exist, but not for the direct command library.
