### ISSUE TITLE
[Feature Request] Update pyusb API

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Eelviny/nxt-python#54]
```

I think that is time to update the usbsock to new PyUSB.
I attach a patch with the changes: there are a few, but need more testings. It 
works in my Ubuntu 13.10 without problem.
Only have a doubt with the "if os.name != 'nt'..", I think that isn't 
necessary, but that must be tested.
I prefer thousands of times GIT over SVN :-), and my patch is over a git-svn 
clone.
```

Original issue reported on code.google.com by `alan...@gmail.com` on 21 May 2013 at 9:24

Attachments:
* [0001-update-usbsock.patch](https://storage.googleapis.com/google-code-attachments/nxt-python/issue-54/comment-0/0001-update-usbsock.patch)

**Comment by Eelviny** [comment]
Patch is entirely outdated - Opened issue #83 to resolve this issue from now on.
