### ISSUE TITLE
[Patch] Use python logging.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Eelviny/nxt-python#64]
```
This patch update the code to use the python logging module.


```

Original issue reported on code.google.com by `n...@chalko.com` on 27 Dec 2013 at 12:36

Attachments:
* [logging-patch.txt](https://storage.googleapis.com/google-code-attachments/nxt-python/issue-64/comment-0/logging-patch.txt)

**Comment by Eelviny** [comment]
This patch is so outdated, that while it would be great to add it, I might as well have to rewrite it.
Going to close this as there's not much that can be done with this particular commit.
Reference to chalko/nxt-python
