### ISSUE TITLE
Test script not Py3 compatible

### ISSUE THREAD

**Issue by Pixdigit** [Eelviny/nxt-python#71]
The nxt_test in scripts is not python3 compatible, while some required libraries are py3 exclusive. Please correct all print statements, so they have "((" and "))".
Also if the try statement fails b is not defined and a NameError is risen.

**Comment by Eelviny** [comment]
Whoops, didn't see that one. I'll give that a quick fix up.
Right now the bigger problem is v3 doesn't work at all, but hey, since I'm here already ;)

**Comment by Pixdigit** [comment]
Turns out ipsock.py, brick.py, bluesock.py, usbsock.py and locator.py are not Py2 compatible … ?
--> http://pastebin.com/iZt2miDh

**Comment by Eelviny** [comment]
Everything in the master branch should by Py3 compatible. Everything in the Python 2 branch, and the latest releases, should be Py2 compatible.
Which are you using? You should be using the latest release.

**Comment by Pixdigit** [comment]
It was pulled directly from the https://github.com/Eelviny/nxt-python repo.

**Comment by Eelviny** [comment]
That'll be why.
1. The latest commits are designed exclusively for Python 3
2. The repository is currently unstable to the point of unusable, and you should use the versions on the releases page.

**Comment by Pixdigit** [comment]
Yes, that should definitely solve the problem. But to avoid further irritation the Master branch could be marked as unstable and the Py2 branch as preferred source since it is best practice to have the preferred version in Master and make branches for in development versions. (Just pointing out. I don't do so really either)
