### ISSUE TITLE
Python 3 <> Python 2 series <> dependencies

### ISSUE THREAD

**Issue by leenaars** [Eelviny/nxt-python#90]
Hi Elvin, 

trying to install this fine project (thanks for maintaining it) on Linux/NixOS. There are two opposing statements I came across. The README says python-nxt only works with Python 3.x (and is currently developed using Python 3.5.1), while the Installation page on the wiki (https://github.com/Eelviny/nxt-python/wiki/Installation) more or less says the opposite. It is not clear to me what dependencies I need to install (I've installed pyusb, pybluez, and pyfantom but I'm still getting a No backend available).

**Comment by Eelviny** [comment]
Hi,

As GitHub is built primarily for development, the development build is featured most prominently on the front page. The build for Python 3.x doesn't work yet (I have hardly any time to develop it).

What you're looking for are the working, stable release versions. This is what is detailed on the Installation page, and the latest stable version runs on Python 2.x.
